# Generated by Django 3.2.5 on 2021-08-10 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_purchase'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('cancelled', 'cancelled'), ('dispated', 'dispated'), ('in_transit', 'in_transit'), ('ready_to_deliver', 'ready_to_deliver'), ('delivered', 'delivered')], default='order_placed', max_length=120)),
                ('user', models.CharField(max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.mobile')),
            ],
        ),
    ]
